name: Folder Structure Workflow Part 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  validate-folder-structure:
    name: Validate folder structure
    runs-on: windows-latest
